FROM python:3.12-slim-bookworm

WORKDIR /app

# Install API dependencies
COPY requirements-api-sklearn.txt .

RUN pip install --no-cache-dir -r requirements-api-sklearn.txt

# Copy application and sklearn model
COPY src/ ./src/
COPY models/fraud_random_forest_top10_sklearn.joblib ./models/

# API port
EXPOSE 8000

# Start FastAPI
CMD ["uvicorn", "src.api.main_sklearn:app", "--host", "0.0.0.0", "--port", "8000"]