name: Deploy Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/992568969638/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-actions-deployer@gen-lang-client-0097541881.iam.gserviceaccount.com"

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fraud-detection-api \
            --image=europe-southwest1-docker.pkg.dev/gen-lang-client-0097541881/fraud-detection/fraud-detection-api:latest \
            --region=europe-southwest1 \
            --platform=managed \
            --allow-unauthenticated \
            --min=0 \
            --max=1 \
            --cpu=1 \
            --memory=2Gi \
            --port=8000
