name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-api.txt
          pip install pytest

      - name: Run tests
        run: |
          python -m pytest -v

  docker:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/992568969638/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-actions-deployer@gen-lang-client-0097541881.iam.gserviceaccount.com"

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t europe-southwest1-docker.pkg.dev/gen-lang-client-0097541881/fraud-detection/fraud-detection-api:latest \
            .

      - name: Push Docker image
        run: |
          docker push \
            europe-southwest1-docker.pkg.dev/gen-lang-client-0097541881/fraud-detection/fraud-detection-api:latest